name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - psycopg2
  - boost 
  - boost-cpp 
  - libboost 
  - swig
  - quantlib 
  - quantlib-python
  - jupyter
  - jupytext
