name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - psycopg2
  - boost==1.74.0
  - boost-cpp==1.74.0
  - swig
  - quantlib==1.27
  - quantlib-python==1.27
  - jupyter
  - jupytext
